name: mobileminer
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  data_connection_checker: ^0.3.4
  http: ^0.12.0
  toast: ^0.1.5
  shared_preferences:
  progress_dialog: ^1.2.0
  numberpicker: ^1.2.0
  material_design_icons_flutter: ^3.2.3895
  cached_network_image: ^2.0.0
  geolocator: ^5.1.3
  geocoder: ^0.2.1
  google_maps_flutter: ^0.5.25
  google_fonts:
  image_picker:
  flutter_cache_manager:
  intl: ^0.16.1
  recase: ^3.0.0
  flutter_speed_dial: ^1.2.5
  flutter_barcode_scanner: ^1.0.0
  image_cropper: ^1.2.2
  webview_flutter: ^0.3.14+1
  random_string: ^1.1.0
  url_launcher: ^5.4.7
  carousel_pro: ^1.0.0
  fab_circular_menu: ^1.0.0
  flutter_spinkit: ^3.1.0

  
  
    
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
        
    - family: Solway
      fonts:
        - asset: fonts/Solway-Bold.ttf
       